# Generated by Django 4.2.2 on 2023-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_integer',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
