# Generated by Django 4.2.2 on 2023-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_user_unique_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('Dispatch', 'Dispatch'), ('SectionOffice', 'Section Office'), ('HOD', 'Head of Department')], max_length=50),
        ),
    ]
