# Generated by Django 4.2.2 on 2023-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
